# Generated by Django 5.1.3 on 2024-11-17 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StructuralUnits',
            fields=[
                ('structural_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_title', models.TextField()),
                ('abbreviated_title', models.CharField(blank=True, max_length=20, null=True)),
                ('head_of_the_unit', models.CharField(max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'structural_units',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True)),
                ('birthday', models.DateField()),
                ('email', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('professor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True)),
                ('degree', models.CharField(blank=True, max_length=15, null=True)),
                ('academic_title', models.CharField(blank=True, max_length=40, null=True)),
                ('current_position', models.CharField(max_length=40)),
                ('experience', models.IntegerField()),
                ('salary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'professors',
            },
        ),
        migrations.CreateModel(
            name='StudentIds',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='orioks.students')),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
            ],
            options={
                'db_table': 'student_ids',
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('field_id', models.UUIDField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('zet', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('structural_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orioks.structuralunits')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orioks.professors')),
            ],
            options={
                'db_table': 'fields',
            },
        ),
        migrations.CreateModel(
            name='StudentsGroups',
            fields=[
                ('students_group_number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('enrolment_status', models.CharField(max_length=12)),
                ('structural_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orioks.structuralunits')),
            ],
            options={
                'db_table': 'students_groups',
            },
        ),
        migrations.AddField(
            model_name='students',
            name='students_group_number',
            field=models.ForeignKey(db_column='students_group_number', on_delete=django.db.models.deletion.DO_NOTHING, to='orioks.studentsgroups'),
        ),
        migrations.CreateModel(
            name='Employments',
            fields=[
                ('structural_unit', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='orioks.structuralunits')),
                ('contract_number', models.IntegerField()),
                ('wage_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orioks.professors')),
            ],
            options={
                'db_table': 'employments',
                'unique_together': {('structural_unit', 'professor')},
            },
        ),
        migrations.CreateModel(
            name='FieldComprehensions',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='orioks.students')),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('field', models.ForeignKey(db_column='field', on_delete=django.db.models.deletion.DO_NOTHING, to='orioks.fields')),
            ],
            options={
                'db_table': 'field_comprehensions',
                'unique_together': {('student', 'field')},
            },
        ),
    ]
